Mix.Task.run("app.start")

alias PcapFileEx.{Filter, HTTP, Packet}

defmodule PcapFileExBench do
  @moduledoc false

  def run(path) do
    Benchee.run(
      %{
        "stream parse (decode: false)" => fn -> parse_raw(path) end,
        "stream parse (decode: true)" => fn -> parse_decoded(path) end,
        "filter UDP packets" => fn -> filter_udp(path) end,
        "filter HTTP POST requests" => fn -> filter_http_post(path) end
      },
      time: 10,
      warmup: 2,
      memory_time: 2,
      formatters: [
        {Benchee.Formatters.Console, extended_statistics: true}
      ]
    )
  end

  defp parse_raw(path) do
    PcapFileEx.stream(path, decode: false)
    |> Enum.reduce({0, 0}, fn packet, {count, bytes} ->
      {count + 1, bytes + byte_size(packet.data)}
    end)
  end

  defp parse_decoded(path) do
    PcapFileEx.stream(path)
    |> Enum.reduce({0, 0, 0}, fn packet, {count, bytes, http_posts} ->
      http_posts =
        if http_post?(packet) do
          http_posts + 1
        else
          http_posts
        end

      {count + 1, bytes + byte_size(packet.data), http_posts}
    end)
  end

  defp filter_udp(path) do
    PcapFileEx.stream(path, decode: false)
    |> Filter.by_protocol(:udp)
    |> Enum.reduce({0, 0}, fn packet, {count, bytes} ->
      {count + 1, bytes + byte_size(packet.data)}
    end)
  end

  defp filter_http_post(path) do
    PcapFileEx.stream(path)
    |> Filter.by_protocol(:http)
    |> Enum.reduce(0, fn packet, acc ->
      if http_post?(packet), do: acc + 1, else: acc
    end)
  end

  defp http_post?(%Packet{} = packet) do
    case packet.decoded do
      %{} = decoded ->
        case Map.get(decoded, :http) do
          %HTTP{type: :request, method: "POST"} -> true
          _ -> fallback_post?(packet)
        end

      _ ->
        fallback_post?(packet)
    end
  end

  defp fallback_post?(packet) do
    case Packet.decode_http(packet) do
      {:ok, %HTTP{type: :request, method: "POST"}} -> true
      _ -> false
    end
  end
end

pcap_path =
  System.get_env("PCAP_BENCH_FILE") ||
    Path.expand("../test/fixtures/large_capture.pcapng", __DIR__)

unless File.exists?(pcap_path) do
  raise ArgumentError,
        "PCAP bench file not found at #{pcap_path}. " <>
          "Set PCAP_BENCH_FILE to point to the large capture generated by capture_heavy_traffic.sh"
end

PcapFileExBench.run(pcap_path)
